from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(881, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 881, 581))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.DropDownListSector2_1 = QtGui.QComboBox(self.tab)
        self.DropDownListSector2_1.setGeometry(QtCore.QRect(30, 40, 251, 22))
        self.DropDownListSector2_1.setObjectName(_fromUtf8("DropDownListSector2_1"))
        self.DropDownListVariable2_1 = QtGui.QComboBox(self.tab)
        self.DropDownListVariable2_1.setGeometry(QtCore.QRect(320, 40, 161, 22))
        self.DropDownListVariable2_1.setObjectName(_fromUtf8("DropDownListVariable2_1"))
        self.ButtonLaunchTranus2_1 = QtGui.QPushButton(self.tab)
        self.ButtonLaunchTranus2_1.setGeometry(QtCore.QRect(730, 170, 101, 23))
        self.ButtonLaunchTranus2_1.setObjectName(_fromUtf8("ButtonLaunchTranus2_1"))
        self.MinValue2_1 = QtGui.QDoubleSpinBox(self.tab)
        self.MinValue2_1.setGeometry(QtCore.QRect(540, 40, 62, 22))
        self.MinValue2_1.setMaximum(107.99)
        self.MinValue2_1.setObjectName(_fromUtf8("MinValue2_1"))
        self.MaxValue2_1 = QtGui.QDoubleSpinBox(self.tab)
        self.MaxValue2_1.setGeometry(QtCore.QRect(640, 40, 62, 22))
        self.MaxValue2_1.setObjectName(_fromUtf8("MaxValue2_1"))
        self.NbIterations2_1 = QtGui.QSpinBox(self.tab)
        self.NbIterations2_1.setGeometry(QtCore.QRect(630, 70, 42, 22))
        self.NbIterations2_1.setObjectName(_fromUtf8("NbIterations2_1"))
        self.LabelMin = QtGui.QLabel(self.tab)
        self.LabelMin.setGeometry(QtCore.QRect(510, 40, 21, 21))
        self.LabelMin.setObjectName(_fromUtf8("LabelMin"))
        self.LabelMax = QtGui.QLabel(self.tab)
        self.LabelMax.setGeometry(QtCore.QRect(610, 43, 46, 20))
        self.LabelMax.setObjectName(_fromUtf8("LabelMax"))
        self.LabelNumIterations = QtGui.QLabel(self.tab)
        self.LabelNumIterations.setGeometry(QtCore.QRect(510, 70, 111, 21))
        self.LabelNumIterations.setObjectName(_fromUtf8("LabelNumIterations"))
        self.LabelSelectionSector = QtGui.QLabel(self.tab)
        self.LabelSelectionSector.setGeometry(QtCore.QRect(30, 10, 121, 16))
        self.LabelSelectionSector.setObjectName(_fromUtf8("LabelSelectionSector"))
        self.LabelSelectionValue = QtGui.QLabel(self.tab)
        self.LabelSelectionValue.setGeometry(QtCore.QRect(320, 10, 161, 16))
        self.LabelSelectionValue.setObjectName(_fromUtf8("LabelSelectionValue"))
        self.LabelCurrentValue = QtGui.QLabel(self.tab)
        self.LabelCurrentValue.setGeometry(QtCore.QRect(310, 90, 81, 16))
        self.LabelCurrentValue.setObjectName(_fromUtf8("LabelCurrentValue"))
        self.LabelDislayCurrentValue2_1 = QtGui.QLabel(self.tab)
        self.LabelDislayCurrentValue2_1.setGeometry(QtCore.QRect(400, 90, 46, 13))
        self.LabelDislayCurrentValue2_1.setText(_fromUtf8(""))
        self.LabelDislayCurrentValue2_1.setObjectName(_fromUtf8("LabelDislayCurrentValue2_1"))
        self.LabelSelectionDisplayIter2_1 = QtGui.QLabel(self.tab)
        self.LabelSelectionDisplayIter2_1.setGeometry(QtCore.QRect(150, 280, 161, 16))
        self.LabelSelectionDisplayIter2_1.setObjectName(_fromUtf8("LabelSelectionDisplayIter2_1"))
        self.DropDownListDisplaySector2_1 = QtGui.QComboBox(self.tab)
        self.DropDownListDisplaySector2_1.setGeometry(QtCore.QRect(150, 250, 181, 22))
        self.DropDownListDisplaySector2_1.setObjectName(_fromUtf8("DropDownListDisplaySector2_1"))
        self.LabelSelectionDisplaySector2_1 = QtGui.QLabel(self.tab)
        self.LabelSelectionDisplaySector2_1.setGeometry(QtCore.QRect(150, 220, 161, 21))
        self.LabelSelectionDisplaySector2_1.setObjectName(_fromUtf8("LabelSelectionDisplaySector2_1"))
        self.DropDownListDisplayIter2_1 = QtGui.QComboBox(self.tab)
        self.DropDownListDisplayIter2_1.setGeometry(QtCore.QRect(150, 300, 181, 22))
        self.DropDownListDisplayIter2_1.setObjectName(_fromUtf8("DropDownListDisplayIter2_1"))
        self.ButtonPlot2_1 = QtGui.QPushButton(self.tab)
        self.ButtonPlot2_1.setGeometry(QtCore.QRect(180, 350, 101, 23))
        self.ButtonPlot2_1.setObjectName(_fromUtf8("ButtonPlot2_1"))
        self.labelVariable2_1 = QtGui.QLabel(self.tab)
        self.labelVariable2_1.setGeometry(QtCore.QRect(30, 300, 111, 16))
        self.labelVariable2_1.setText(_fromUtf8(""))
        self.labelVariable2_1.setObjectName(_fromUtf8("labelVariable2_1"))
        self.LabelNbIter = QtGui.QLabel(self.tab)
        self.LabelNbIter.setGeometry(QtCore.QRect(20, 170, 151, 16))
        self.LabelNbIter.setObjectName(_fromUtf8("LabelNbIter"))
        self.NbIterLcal2_1 = QtGui.QSpinBox(self.tab)
        self.NbIterLcal2_1.setGeometry(QtCore.QRect(170, 170, 51, 20))
        self.NbIterLcal2_1.setMaximum(1000000000)
        self.NbIterLcal2_1.setObjectName(_fromUtf8("NbIterLcal2_1"))
        self.LabelConvFactor = QtGui.QLabel(self.tab)
        self.LabelConvFactor.setGeometry(QtCore.QRect(240, 170, 131, 16))
        self.LabelConvFactor.setObjectName(_fromUtf8("LabelConvFactor"))
        self.LabelSmoothFactor = QtGui.QLabel(self.tab)
        self.LabelSmoothFactor.setGeometry(QtCore.QRect(470, 170, 111, 16))
        self.LabelSmoothFactor.setObjectName(_fromUtf8("LabelSmoothFactor"))
        self.SmoothingFactor2_1 = QtGui.QDoubleSpinBox(self.tab)
        self.SmoothingFactor2_1.setGeometry(QtCore.QRect(580, 170, 62, 22))
        self.SmoothingFactor2_1.setMaximum(107.99)
        self.SmoothingFactor2_1.setObjectName(_fromUtf8("SmoothingFactor2_1"))
        self.ConvFactor2_1 = QtGui.QSpinBox(self.tab)
        self.ConvFactor2_1.setGeometry(QtCore.QRect(370, 170, 51, 20))
        self.ConvFactor2_1.setMaximum(10)
        self.ConvFactor2_1.setObjectName(_fromUtf8("ConvFactor2_1"))
        self.buttonResults2_1 = QtGui.QPushButton(self.tab)
        self.buttonResults2_1.setGeometry(QtCore.QRect(340, 250, 81, 23))
        self.buttonResults2_1.setObjectName(_fromUtf8("buttonResults2_1"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.DropDownListSector_22 = QtGui.QComboBox(self.tab_2)
        self.DropDownListSector_22.setGeometry(QtCore.QRect(40, 40, 281, 22))
        self.DropDownListSector_22.setObjectName(_fromUtf8("DropDownListSector_22"))
        self.DropDownListInput2_2 = QtGui.QComboBox(self.tab_2)
        self.DropDownListInput2_2.setGeometry(QtCore.QRect(40, 110, 281, 22))
        self.DropDownListInput2_2.setObjectName(_fromUtf8("DropDownListInput2_2"))
        self.DropDownListVariable_22 = QtGui.QComboBox(self.tab_2)
        self.DropDownListVariable_22.setGeometry(QtCore.QRect(380, 70, 161, 22))
        self.DropDownListVariable_22.setObjectName(_fromUtf8("DropDownListVariable_22"))
        self.MinValue_22 = QtGui.QDoubleSpinBox(self.tab_2)
        self.MinValue_22.setGeometry(QtCore.QRect(630, 60, 62, 22))
        self.MinValue_22.setObjectName(_fromUtf8("MinValue_22"))
        self.MaxValue_22 = QtGui.QDoubleSpinBox(self.tab_2)
        self.MaxValue_22.setGeometry(QtCore.QRect(760, 60, 62, 22))
        self.MaxValue_22.setObjectName(_fromUtf8("MaxValue_22"))
        self.NbIterations_22 = QtGui.QSpinBox(self.tab_2)
        self.NbIterations_22.setGeometry(QtCore.QRect(740, 100, 42, 22))
        self.NbIterations_22.setObjectName(_fromUtf8("NbIterations_22"))
        self.LabelSelectionSector2 = QtGui.QLabel(self.tab_2)
        self.LabelSelectionSector2.setGeometry(QtCore.QRect(40, 10, 121, 16))
        self.LabelSelectionSector2.setObjectName(_fromUtf8("LabelSelectionSector2"))
        self.LabelSelectionInputSector = QtGui.QLabel(self.tab_2)
        self.LabelSelectionInputSector.setGeometry(QtCore.QRect(40, 90, 121, 16))
        self.LabelSelectionInputSector.setObjectName(_fromUtf8("LabelSelectionInputSector"))
        self.LabelSelectionValue_2 = QtGui.QLabel(self.tab_2)
        self.LabelSelectionValue_2.setGeometry(QtCore.QRect(380, 50, 161, 16))
        self.LabelSelectionValue_2.setObjectName(_fromUtf8("LabelSelectionValue_2"))
        self.LabelMin_2 = QtGui.QLabel(self.tab_2)
        self.LabelMin_2.setGeometry(QtCore.QRect(600, 60, 21, 21))
        self.LabelMin_2.setObjectName(_fromUtf8("LabelMin_2"))
        self.LabelMax_2 = QtGui.QLabel(self.tab_2)
        self.LabelMax_2.setGeometry(QtCore.QRect(720, 60, 46, 20))
        self.LabelMax_2.setObjectName(_fromUtf8("LabelMax_2"))
        self.LabelNumIterations_2 = QtGui.QLabel(self.tab_2)
        self.LabelNumIterations_2.setGeometry(QtCore.QRect(620, 100, 111, 21))
        self.LabelNumIterations_2.setObjectName(_fromUtf8("LabelNumIterations_2"))
        self.ButtonLaunchTranus2_2 = QtGui.QPushButton(self.tab_2)
        self.ButtonLaunchTranus2_2.setGeometry(QtCore.QRect(710, 200, 101, 23))
        self.ButtonLaunchTranus2_2.setObjectName(_fromUtf8("ButtonLaunchTranus2_2"))
        self.LabelCurrentValue_2 = QtGui.QLabel(self.tab_2)
        self.LabelCurrentValue_2.setGeometry(QtCore.QRect(380, 110, 81, 16))
        self.LabelCurrentValue_2.setObjectName(_fromUtf8("LabelCurrentValue_2"))
        self.LabelDislayCurrentValue2_2 = QtGui.QLabel(self.tab_2)
        self.LabelDislayCurrentValue2_2.setGeometry(QtCore.QRect(470, 110, 46, 13))
        self.LabelDislayCurrentValue2_2.setText(_fromUtf8(""))
        self.LabelDislayCurrentValue2_2.setObjectName(_fromUtf8("LabelDislayCurrentValue2_2"))
        self.LabelSelectionDisplayIter2_2 = QtGui.QLabel(self.tab_2)
        self.LabelSelectionDisplayIter2_2.setGeometry(QtCore.QRect(160, 300, 161, 16))
        self.LabelSelectionDisplayIter2_2.setObjectName(_fromUtf8("LabelSelectionDisplayIter2_2"))
        self.DropDownListDisplaySector2_2 = QtGui.QComboBox(self.tab_2)
        self.DropDownListDisplaySector2_2.setGeometry(QtCore.QRect(155, 259, 181, 22))
        self.DropDownListDisplaySector2_2.setObjectName(_fromUtf8("DropDownListDisplaySector2_2"))
        self.LabelSelectionDisplaySector2_2 = QtGui.QLabel(self.tab_2)
        self.LabelSelectionDisplaySector2_2.setGeometry(QtCore.QRect(155, 239, 161, 16))
        self.LabelSelectionDisplaySector2_2.setObjectName(_fromUtf8("LabelSelectionDisplaySector2_2"))
        self.DropDownListDisplayIter2_2 = QtGui.QComboBox(self.tab_2)
        self.DropDownListDisplayIter2_2.setGeometry(QtCore.QRect(155, 319, 181, 22))
        self.DropDownListDisplayIter2_2.setObjectName(_fromUtf8("DropDownListDisplayIter2_2"))
        self.ButtonPlot2_2 = QtGui.QPushButton(self.tab_2)
        self.ButtonPlot2_2.setGeometry(QtCore.QRect(180, 360, 101, 23))
        self.ButtonPlot2_2.setObjectName(_fromUtf8("ButtonPlot2_2"))
        self.labelVariable2_2 = QtGui.QLabel(self.tab_2)
        self.labelVariable2_2.setGeometry(QtCore.QRect(30, 320, 111, 16))
        self.labelVariable2_2.setText(_fromUtf8(""))
        self.labelVariable2_2.setObjectName(_fromUtf8("labelVariable2_2"))
        self.LabelSmoothFactor_2 = QtGui.QLabel(self.tab_2)
        self.LabelSmoothFactor_2.setGeometry(QtCore.QRect(480, 200, 111, 16))
        self.LabelSmoothFactor_2.setObjectName(_fromUtf8("LabelSmoothFactor_2"))
        self.LabelNbIter_2 = QtGui.QLabel(self.tab_2)
        self.LabelNbIter_2.setGeometry(QtCore.QRect(30, 200, 151, 16))
        self.LabelNbIter_2.setObjectName(_fromUtf8("LabelNbIter_2"))
        self.SmoothingFactor2_2 = QtGui.QDoubleSpinBox(self.tab_2)
        self.SmoothingFactor2_2.setGeometry(QtCore.QRect(590, 200, 62, 22))
        self.SmoothingFactor2_2.setMaximum(107.99)
        self.SmoothingFactor2_2.setObjectName(_fromUtf8("SmoothingFactor2_2"))
        self.NbIterLcal2_2 = QtGui.QSpinBox(self.tab_2)
        self.NbIterLcal2_2.setGeometry(QtCore.QRect(180, 200, 51, 20))
        self.NbIterLcal2_2.setMaximum(1000000000)
        self.NbIterLcal2_2.setObjectName(_fromUtf8("NbIterLcal2_2"))
        self.LabelConvFactor_2 = QtGui.QLabel(self.tab_2)
        self.LabelConvFactor_2.setGeometry(QtCore.QRect(260, 200, 131, 16))
        self.LabelConvFactor_2.setObjectName(_fromUtf8("LabelConvFactor_2"))
        self.ConvFactor2_2 = QtGui.QSpinBox(self.tab_2)
        self.ConvFactor2_2.setGeometry(QtCore.QRect(390, 200, 51, 20))
        self.ConvFactor2_2.setMaximum(10)
        self.ConvFactor2_2.setObjectName(_fromUtf8("ConvFactor2_2"))
        self.buttonResults2_2 = QtGui.QPushButton(self.tab_2)
        self.buttonResults2_2.setGeometry(QtCore.QRect(340, 260, 81, 23))
        self.buttonResults2_2.setObjectName(_fromUtf8("buttonResults2_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.ButtonLaunchTranus2_3 = QtGui.QPushButton(self.tab_3)
        self.ButtonLaunchTranus2_3.setGeometry(QtCore.QRect(730, 200, 101, 23))
        self.ButtonLaunchTranus2_3.setObjectName(_fromUtf8("ButtonLaunchTranus2_3"))
        self.DropDownListSubstitution = QtGui.QComboBox(self.tab_3)
        self.DropDownListSubstitution.setGeometry(QtCore.QRect(40, 130, 281, 22))
        self.DropDownListSubstitution.setObjectName(_fromUtf8("DropDownListSubstitution"))
        self.DropDownListSector2_3 = QtGui.QComboBox(self.tab_3)
        self.DropDownListSector2_3.setGeometry(QtCore.QRect(40, 60, 281, 22))
        self.DropDownListSector2_3.setObjectName(_fromUtf8("DropDownListSector2_3"))
        self.LabelSelectionInputSector_3 = QtGui.QLabel(self.tab_3)
        self.LabelSelectionInputSector_3.setGeometry(QtCore.QRect(40, 110, 191, 16))
        self.LabelSelectionInputSector_3.setObjectName(_fromUtf8("LabelSelectionInputSector_3"))
        self.LabelSelectionSector2_2 = QtGui.QLabel(self.tab_3)
        self.LabelSelectionSector2_2.setGeometry(QtCore.QRect(40, 30, 121, 16))
        self.LabelSelectionSector2_2.setObjectName(_fromUtf8("LabelSelectionSector2_2"))
        self.DropDownListVariable2_3 = QtGui.QComboBox(self.tab_3)
        self.DropDownListVariable2_3.setGeometry(QtCore.QRect(380, 90, 161, 22))
        self.DropDownListVariable2_3.setObjectName(_fromUtf8("DropDownListVariable2_3"))
        self.LabelMin_7 = QtGui.QLabel(self.tab_3)
        self.LabelMin_7.setGeometry(QtCore.QRect(600, 80, 21, 21))
        self.LabelMin_7.setObjectName(_fromUtf8("LabelMin_7"))
        self.LabelNumIterations_7 = QtGui.QLabel(self.tab_3)
        self.LabelNumIterations_7.setGeometry(QtCore.QRect(620, 120, 111, 21))
        self.LabelNumIterations_7.setObjectName(_fromUtf8("LabelNumIterations_7"))
        self.NbIterations2_3 = QtGui.QSpinBox(self.tab_3)
        self.NbIterations2_3.setGeometry(QtCore.QRect(740, 120, 42, 22))
        self.NbIterations2_3.setObjectName(_fromUtf8("NbIterations2_3"))
        self.MaxValue2_3 = QtGui.QDoubleSpinBox(self.tab_3)
        self.MaxValue2_3.setGeometry(QtCore.QRect(760, 80, 62, 22))
        self.MaxValue2_3.setObjectName(_fromUtf8("MaxValue2_3"))
        self.LabelSelectionValue_7 = QtGui.QLabel(self.tab_3)
        self.LabelSelectionValue_7.setGeometry(QtCore.QRect(380, 70, 161, 16))
        self.LabelSelectionValue_7.setObjectName(_fromUtf8("LabelSelectionValue_7"))
        self.MinValue2_3 = QtGui.QDoubleSpinBox(self.tab_3)
        self.MinValue2_3.setGeometry(QtCore.QRect(630, 80, 62, 22))
        self.MinValue2_3.setObjectName(_fromUtf8("MinValue2_3"))
        self.LabelMax_7 = QtGui.QLabel(self.tab_3)
        self.LabelMax_7.setGeometry(QtCore.QRect(720, 80, 46, 20))
        self.LabelMax_7.setObjectName(_fromUtf8("LabelMax_7"))
        self.LabelCurrentValue_3 = QtGui.QLabel(self.tab_3)
        self.LabelCurrentValue_3.setGeometry(QtCore.QRect(380, 130, 81, 16))
        self.LabelCurrentValue_3.setObjectName(_fromUtf8("LabelCurrentValue_3"))
        self.LabelDislayCurrentValue2_3 = QtGui.QLabel(self.tab_3)
        self.LabelDislayCurrentValue2_3.setGeometry(QtCore.QRect(470, 130, 46, 13))
        self.LabelDislayCurrentValue2_3.setText(_fromUtf8(""))
        self.LabelDislayCurrentValue2_3.setObjectName(_fromUtf8("LabelDislayCurrentValue2_3"))
        self.LabelSelectionDisplayIter2_3 = QtGui.QLabel(self.tab_3)
        self.LabelSelectionDisplayIter2_3.setGeometry(QtCore.QRect(165, 309, 161, 16))
        self.LabelSelectionDisplayIter2_3.setObjectName(_fromUtf8("LabelSelectionDisplayIter2_3"))
        self.DropDownListDisplaySector2_3 = QtGui.QComboBox(self.tab_3)
        self.DropDownListDisplaySector2_3.setGeometry(QtCore.QRect(165, 279, 181, 22))
        self.DropDownListDisplaySector2_3.setObjectName(_fromUtf8("DropDownListDisplaySector2_3"))
        self.LabelSelectionDisplaySector2_3 = QtGui.QLabel(self.tab_3)
        self.LabelSelectionDisplaySector2_3.setGeometry(QtCore.QRect(165, 259, 161, 16))
        self.LabelSelectionDisplaySector2_3.setObjectName(_fromUtf8("LabelSelectionDisplaySector2_3"))
        self.DropDownListDisplayIter2_3 = QtGui.QComboBox(self.tab_3)
        self.DropDownListDisplayIter2_3.setGeometry(QtCore.QRect(165, 339, 181, 22))
        self.DropDownListDisplayIter2_3.setObjectName(_fromUtf8("DropDownListDisplayIter2_3"))
        self.ButtonPlot2_3 = QtGui.QPushButton(self.tab_3)
        self.ButtonPlot2_3.setGeometry(QtCore.QRect(200, 390, 101, 23))
        self.ButtonPlot2_3.setObjectName(_fromUtf8("ButtonPlot2_3"))
        self.labelVariable2_3 = QtGui.QLabel(self.tab_3)
        self.labelVariable2_3.setGeometry(QtCore.QRect(40, 340, 111, 16))
        self.labelVariable2_3.setText(_fromUtf8(""))
        self.labelVariable2_3.setObjectName(_fromUtf8("labelVariable2_3"))
        self.LabelSmoothFactor_3 = QtGui.QLabel(self.tab_3)
        self.LabelSmoothFactor_3.setGeometry(QtCore.QRect(510, 200, 111, 16))
        self.LabelSmoothFactor_3.setObjectName(_fromUtf8("LabelSmoothFactor_3"))
        self.LabelNbIter_3 = QtGui.QLabel(self.tab_3)
        self.LabelNbIter_3.setGeometry(QtCore.QRect(60, 200, 151, 16))
        self.LabelNbIter_3.setObjectName(_fromUtf8("LabelNbIter_3"))
        self.SmoothingFactor2_3 = QtGui.QDoubleSpinBox(self.tab_3)
        self.SmoothingFactor2_3.setGeometry(QtCore.QRect(620, 200, 62, 22))
        self.SmoothingFactor2_3.setMaximum(107.99)
        self.SmoothingFactor2_3.setObjectName(_fromUtf8("SmoothingFactor2_3"))
        self.NbIterLcal2_3 = QtGui.QSpinBox(self.tab_3)
        self.NbIterLcal2_3.setGeometry(QtCore.QRect(210, 200, 51, 20))
        self.NbIterLcal2_3.setMaximum(1000000000)
        self.NbIterLcal2_3.setObjectName(_fromUtf8("NbIterLcal2_3"))
        self.LabelConvFactor_3 = QtGui.QLabel(self.tab_3)
        self.LabelConvFactor_3.setGeometry(QtCore.QRect(280, 200, 131, 16))
        self.LabelConvFactor_3.setObjectName(_fromUtf8("LabelConvFactor_3"))
        self.ConvFactor2_3 = QtGui.QSpinBox(self.tab_3)
        self.ConvFactor2_3.setGeometry(QtCore.QRect(410, 200, 51, 20))
        self.ConvFactor2_3.setMaximum(10)
        self.ConvFactor2_3.setObjectName(_fromUtf8("ConvFactor2_3"))
        self.buttonResults2_3 = QtGui.QPushButton(self.tab_3)
        self.buttonResults2_3.setGeometry(QtCore.QRect(350, 280, 81, 23))
        self.buttonResults2_3.setObjectName(_fromUtf8("buttonResults2_3"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.ButtonLaunchTranus3_2 = QtGui.QPushButton(self.tab_4)
        self.ButtonLaunchTranus3_2.setGeometry(QtCore.QRect(750, 180, 101, 23))
        self.ButtonLaunchTranus3_2.setObjectName(_fromUtf8("ButtonLaunchTranus3_2"))
        self.DropDownListInput3_2 = QtGui.QComboBox(self.tab_4)
        self.DropDownListInput3_2.setGeometry(QtCore.QRect(30, 130, 281, 22))
        self.DropDownListInput3_2.setObjectName(_fromUtf8("DropDownListInput3_2"))
        self.DropDownListSector3_2 = QtGui.QComboBox(self.tab_4)
        self.DropDownListSector3_2.setGeometry(QtCore.QRect(30, 60, 281, 22))
        self.DropDownListSector3_2.setObjectName(_fromUtf8("DropDownListSector3_2"))
        self.LabelSelectionInputSector_2 = QtGui.QLabel(self.tab_4)
        self.LabelSelectionInputSector_2.setGeometry(QtCore.QRect(30, 110, 161, 16))
        self.LabelSelectionInputSector_2.setObjectName(_fromUtf8("LabelSelectionInputSector_2"))
        self.LabelSelectionSector3_2 = QtGui.QLabel(self.tab_4)
        self.LabelSelectionSector3_2.setGeometry(QtCore.QRect(30, 30, 141, 16))
        self.LabelSelectionSector3_2.setObjectName(_fromUtf8("LabelSelectionSector3_2"))
        self.DropDownListVariable3_2 = QtGui.QComboBox(self.tab_4)
        self.DropDownListVariable3_2.setGeometry(QtCore.QRect(390, 90, 161, 22))
        self.DropDownListVariable3_2.setObjectName(_fromUtf8("DropDownListVariable3_2"))
        self.LabelMin_3 = QtGui.QLabel(self.tab_4)
        self.LabelMin_3.setGeometry(QtCore.QRect(610, 80, 21, 21))
        self.LabelMin_3.setObjectName(_fromUtf8("LabelMin_3"))
        self.LabelNumIterations_3 = QtGui.QLabel(self.tab_4)
        self.LabelNumIterations_3.setGeometry(QtCore.QRect(630, 120, 111, 21))
        self.LabelNumIterations_3.setObjectName(_fromUtf8("LabelNumIterations_3"))
        self.MaxValue3_2 = QtGui.QDoubleSpinBox(self.tab_4)
        self.MaxValue3_2.setGeometry(QtCore.QRect(770, 80, 62, 22))
        self.MaxValue3_2.setObjectName(_fromUtf8("MaxValue3_2"))
        self.NbIterations3_2 = QtGui.QSpinBox(self.tab_4)
        self.NbIterations3_2.setGeometry(QtCore.QRect(750, 120, 42, 22))
        self.NbIterations3_2.setObjectName(_fromUtf8("NbIterations3_2"))
        self.LabelSelectionValue_3 = QtGui.QLabel(self.tab_4)
        self.LabelSelectionValue_3.setGeometry(QtCore.QRect(390, 70, 161, 16))
        self.LabelSelectionValue_3.setObjectName(_fromUtf8("LabelSelectionValue_3"))
        self.MinValue3_2 = QtGui.QDoubleSpinBox(self.tab_4)
        self.MinValue3_2.setGeometry(QtCore.QRect(640, 80, 62, 22))
        self.MinValue3_2.setObjectName(_fromUtf8("MinValue3_2"))
        self.LabelMax_3 = QtGui.QLabel(self.tab_4)
        self.LabelMax_3.setGeometry(QtCore.QRect(730, 80, 46, 20))
        self.LabelMax_3.setObjectName(_fromUtf8("LabelMax_3"))
        self.LabelCurrentValue_4 = QtGui.QLabel(self.tab_4)
        self.LabelCurrentValue_4.setGeometry(QtCore.QRect(390, 130, 81, 16))
        self.LabelCurrentValue_4.setObjectName(_fromUtf8("LabelCurrentValue_4"))
        self.LabelDislayCurrentValue3_2 = QtGui.QLabel(self.tab_4)
        self.LabelDislayCurrentValue3_2.setGeometry(QtCore.QRect(480, 130, 46, 13))
        self.LabelDislayCurrentValue3_2.setText(_fromUtf8(""))
        self.LabelDislayCurrentValue3_2.setObjectName(_fromUtf8("LabelDislayCurrentValue3_2"))
        self.DropDownListDisplaySector3_2 = QtGui.QComboBox(self.tab_4)
        self.DropDownListDisplaySector3_2.setGeometry(QtCore.QRect(180, 270, 181, 22))
        self.DropDownListDisplaySector3_2.setObjectName(_fromUtf8("DropDownListDisplaySector3_2"))
        self.DropDownListDisplayIter3_2 = QtGui.QComboBox(self.tab_4)
        self.DropDownListDisplayIter3_2.setGeometry(QtCore.QRect(180, 330, 181, 22))
        self.DropDownListDisplayIter3_2.setObjectName(_fromUtf8("DropDownListDisplayIter3_2"))
        self.LabelSelectionDisplaySector3_2 = QtGui.QLabel(self.tab_4)
        self.LabelSelectionDisplaySector3_2.setGeometry(QtCore.QRect(180, 250, 161, 16))
        self.LabelSelectionDisplaySector3_2.setObjectName(_fromUtf8("LabelSelectionDisplaySector3_2"))
        self.LabelSelectionDisplayIter3_2 = QtGui.QLabel(self.tab_4)
        self.LabelSelectionDisplayIter3_2.setGeometry(QtCore.QRect(180, 300, 161, 16))
        self.LabelSelectionDisplayIter3_2.setObjectName(_fromUtf8("LabelSelectionDisplayIter3_2"))
        self.ButtonPlot3_2 = QtGui.QPushButton(self.tab_4)
        self.ButtonPlot3_2.setGeometry(QtCore.QRect(210, 380, 101, 23))
        self.ButtonPlot3_2.setObjectName(_fromUtf8("ButtonPlot3_2"))
        self.labelVariable3_2 = QtGui.QLabel(self.tab_4)
        self.labelVariable3_2.setGeometry(QtCore.QRect(50, 330, 111, 16))
        self.labelVariable3_2.setText(_fromUtf8(""))
        self.labelVariable3_2.setObjectName(_fromUtf8("labelVariable3_2"))
        self.LabelSmoothFactor_4 = QtGui.QLabel(self.tab_4)
        self.LabelSmoothFactor_4.setGeometry(QtCore.QRect(520, 180, 111, 16))
        self.LabelSmoothFactor_4.setObjectName(_fromUtf8("LabelSmoothFactor_4"))
        self.LabelNbIter_4 = QtGui.QLabel(self.tab_4)
        self.LabelNbIter_4.setGeometry(QtCore.QRect(70, 180, 151, 16))
        self.LabelNbIter_4.setObjectName(_fromUtf8("LabelNbIter_4"))
        self.SmoothingFactor3_2 = QtGui.QDoubleSpinBox(self.tab_4)
        self.SmoothingFactor3_2.setGeometry(QtCore.QRect(630, 180, 62, 22))
        self.SmoothingFactor3_2.setMaximum(107.99)
        self.SmoothingFactor3_2.setObjectName(_fromUtf8("SmoothingFactor3_2"))
        self.NbIterLcal3_2 = QtGui.QSpinBox(self.tab_4)
        self.NbIterLcal3_2.setGeometry(QtCore.QRect(220, 180, 51, 20))
        self.NbIterLcal3_2.setMaximum(1000000000)
        self.NbIterLcal3_2.setObjectName(_fromUtf8("NbIterLcal3_2"))
        self.LabelConvFactor_4 = QtGui.QLabel(self.tab_4)
        self.LabelConvFactor_4.setGeometry(QtCore.QRect(290, 180, 131, 16))
        self.LabelConvFactor_4.setObjectName(_fromUtf8("LabelConvFactor_4"))
        self.ConvFactor3_2 = QtGui.QSpinBox(self.tab_4)
        self.ConvFactor3_2.setGeometry(QtCore.QRect(420, 180, 51, 20))
        self.ConvFactor3_2.setMaximum(10)
        self.ConvFactor3_2.setObjectName(_fromUtf8("ConvFactor3_2"))
        self.buttonResults3_2 = QtGui.QPushButton(self.tab_4)
        self.buttonResults3_2.setGeometry(QtCore.QRect(370, 270, 81, 23))
        self.buttonResults3_2.setObjectName(_fromUtf8("buttonResults3_2"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 881, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.ButtonLaunchTranus2_1.setText(_translate("MainWindow", "Launch TRANUS", None))
        self.LabelMin.setText(_translate("MainWindow", "Min :", None))
        self.LabelMax.setText(_translate("MainWindow", "Max :", None))
        self.LabelNumIterations.setText(_translate("MainWindow", "Number of iterations :", None))
        self.LabelSelectionSector.setText(_translate("MainWindow", "Selection of the sector :", None))
        self.LabelSelectionValue.setText(_translate("MainWindow", "Selection of the value to change :", None))
        self.LabelCurrentValue.setText(_translate("MainWindow", "Current Value :", None))
        self.LabelSelectionDisplayIter2_1.setText(_translate("MainWindow", "Selection of the iteration :", None))
        self.LabelSelectionDisplaySector2_1.setText(_translate("MainWindow", "Selection of the sector :", None))
        self.ButtonPlot2_1.setText(_translate("MainWindow", "Generate graph", None))
        self.LabelNbIter.setText(_translate("MainWindow", "Number of iterations for Lcal :", None))
        self.LabelConvFactor.setText(_translate("MainWindow", "Convergence factor : 1E -", None))
        self.LabelSmoothFactor.setText(_translate("MainWindow", "Smoothing factor :", None))
        self.buttonResults2_1.setText(_translate("MainWindow", "Display Results", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Zone 2.1 Locational Utility Function Parameters", None))
        self.LabelSelectionSector2.setText(_translate("MainWindow", "Selection of the sector :", None))
        self.LabelSelectionInputSector.setText(_translate("MainWindow", "Selection of the input :", None))
        self.LabelSelectionValue_2.setText(_translate("MainWindow", "Selection of the value to change :", None))
        self.LabelMin_2.setText(_translate("MainWindow", "Min :", None))
        self.LabelMax_2.setText(_translate("MainWindow", "Max :", None))
        self.LabelNumIterations_2.setText(_translate("MainWindow", "Number of iterations :", None))
        self.ButtonLaunchTranus2_2.setText(_translate("MainWindow", "Launch TRANUS", None))
        self.LabelCurrentValue_2.setText(_translate("MainWindow", "Current Value :", None))
        self.LabelSelectionDisplayIter2_2.setText(_translate("MainWindow", "Selection of the iteration :", None))
        self.LabelSelectionDisplaySector2_2.setText(_translate("MainWindow", "Selection of the sector :", None))
        self.ButtonPlot2_2.setText(_translate("MainWindow", "Generate graph", None))
        self.LabelSmoothFactor_2.setText(_translate("MainWindow", "Smoothing factor :", None))
        self.LabelNbIter_2.setText(_translate("MainWindow", "Number of iterations for Lcal :", None))
        self.LabelConvFactor_2.setText(_translate("MainWindow", "Convergence factor : 1E -", None))
        self.buttonResults2_2.setText(_translate("MainWindow", "Display Results", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Zone 2.2 Demand Function Parameters", None))
        self.ButtonLaunchTranus2_3.setText(_translate("MainWindow", "Launch TRANUS", None))
        self.LabelSelectionInputSector_3.setText(_translate("MainWindow", "Selection of the sector of substitution :", None))
        self.LabelSelectionSector2_2.setText(_translate("MainWindow", "Selection of the sector :", None))
        self.LabelMin_7.setText(_translate("MainWindow", "Min :", None))
        self.LabelNumIterations_7.setText(_translate("MainWindow", "Number of iterations :", None))
        self.LabelSelectionValue_7.setText(_translate("MainWindow", "Selection of the value to change :", None))
        self.LabelMax_7.setText(_translate("MainWindow", "Max :", None))
        self.LabelCurrentValue_3.setText(_translate("MainWindow", "Current Value :", None))
        self.LabelSelectionDisplayIter2_3.setText(_translate("MainWindow", "Selection of the iteration :", None))
        self.LabelSelectionDisplaySector2_3.setText(_translate("MainWindow", "Selection of the sector :", None))
        self.ButtonPlot2_3.setText(_translate("MainWindow", "Generate graph", None))
        self.LabelSmoothFactor_3.setText(_translate("MainWindow", "Smoothing factor :", None))
        self.LabelNbIter_3.setText(_translate("MainWindow", "Number of iterations for Lcal :", None))
        self.LabelConvFactor_3.setText(_translate("MainWindow", "Convergence factor : 1E -", None))
        self.buttonResults2_3.setText(_translate("MainWindow", "Display Results", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Zone 2.3 Demand Substitutions", None))
        self.ButtonLaunchTranus3_2.setText(_translate("MainWindow", "Launch TRANUS", None))
        self.LabelSelectionInputSector_2.setText(_translate("MainWindow", "Selection of the second sector :", None))
        self.LabelSelectionSector3_2.setText(_translate("MainWindow", "Selection of the first sector :", None))
        self.LabelMin_3.setText(_translate("MainWindow", "Min :", None))
        self.LabelNumIterations_3.setText(_translate("MainWindow", "Number of iterations :", None))
        self.LabelSelectionValue_3.setText(_translate("MainWindow", "Selection of the value to change :", None))
        self.LabelMax_3.setText(_translate("MainWindow", "Max :", None))
        self.LabelCurrentValue_4.setText(_translate("MainWindow", "Current Value :", None))
        self.LabelSelectionDisplaySector3_2.setText(_translate("MainWindow", "Selection of the sector :", None))
        self.LabelSelectionDisplayIter3_2.setText(_translate("MainWindow", "Selection of the iteration :", None))
        self.ButtonPlot3_2.setText(_translate("MainWindow", "Generate graph", None))
        self.LabelSmoothFactor_4.setText(_translate("MainWindow", "Smoothing factor :", None))
        self.LabelNbIter_4.setText(_translate("MainWindow", "Number of iterations for Lcal :", None))
        self.LabelConvFactor_4.setText(_translate("MainWindow", "Convergence factor : 1E -", None))
        self.buttonResults3_2.setText(_translate("MainWindow", "Display Results", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Zone 3.2 Atractors for Induced Production", None))

